### ISSUE TITLE
Search result

### ISSUE THREAD

**Issue by Heater711** [xenPanda/DCS_Stats#3]
Hi,
trying to search a pilot, get this error:

Warning: Missing argument 4 for get_column_sum(), called in /home/xolnfxtn/public_html/ACW_Stats/searchPlayers.php on line 58 and defined in /home/xolnfxtn/public_html/ACW_Stats/includes.php on line 94

Warning: Missing argument 5 for get_kills_total(), called in /home/xolnfxtn/public_html/ACW_Stats/searchPlayers.php on line 63 and defined in /home/xolnfxtn/public_html/ACW_Stats/includes.php on line 172

**Comment by xenPanda** [comment]
I am not able to replicate the problem you are having. Can you tell me what version numbers are at the top of the following files:
searchPlayers.php
includes.php

**Comment by Heater711** [comment]
Filename: searchPlayers.php
  Version: 0.0.1

  Filename: includes.php
  Version: 0.0.3

**Comment by xenPanda** [comment]
Been a bit busy with other projects, and haven't had time to look at this. I should be able to get to it after next week.

**Comment by xenPanda** [comment]
I believe this has now been fixed. You should only need to get the new searchPlayers.php from the slmod7.6 repository and replace the searchPlayers.php file on your server with it.
